version: "3.8"
services:
    ngrok:
        image: wernight/ngrok:latest
        ports:
        - 4040:4040
        # command: ngrok http atlantis:4141
        environment:
            # https://dashboard.ngrok.com/get-started/your-authtoken
            NGROK_AUTH: $NGROK_AUTH_TOKEN
            NGROK_PROTOCOL: http
            NGROK_PORT: atlantis:4141
            NGROK_DEBUG: true
        # depends_on:
        # - atlantis
    # redis:
    #     image: redis:7.0-alpine
    #     restart: always
    #     ports:
    #     - '6379:6379'
    #     command: redis-server --save 20 1 --loglevel warning --requirepass test123
    #     volumes: 
    #     - redis:/data
    atlantis:
        # depends_on:
        # - redis
        image: flaconi/atlantis-terragrunt:0.22.3-1.3.8-0.43.2
        ports:
        - 4141:4141
        command: server --gh-user=$GH_USERNAME --gh-token=$GH_ATLANTIS_TOKEN --repo-allowlist=$REPO_WHITELIST --gh-webhook-secret=$WEBHOOK_SECRET