version: "3.8"
services:
    ngrok:
        image: wernight/ngrok:latest
        ports:
        - 4040:4040
        # command: ngrok http atlantis:4141
        environment:
            # https://dashboard.ngrok.com/get-started/your-authtoken
            NGROK_AUTH: $NGROK_AUTH_TOKEN
            NGROK_PROTOCOL: http
            NGROK_PORT: atlantis:4141
            NGROK_DEBUG: true
        # depends_on:
        # - atlantis
    # redis:
    #     image: redis:7.0-alpine
    #     restart: always
    #     ports:
    #     - '6379:6379'
    #     command: redis-server --save 20 1 --loglevel warning --requirepass test123
    #     volumes: 
    #     - redis:/data
    atlantis:
        # depends_on:
        # - redis
        image: atlantis-terragrunt:custom
        ports:
        - 4141:4141
        # command: server --gh-user=$GH_USERNAME --gh-token=$GH_ATLANTIS_TOKEN --repo-allowlist=$REPO_WHITELIST --gh-webhook-secret=$WEBHOOK_SECRET --repo-config='/etc/atlantis/repo.yaml'
        volumes:
        - ${PWD}/repo.yaml:/etc/atlantis/repo.yaml
        environment:
            ATLANTIS_GH_USER: $GH_USERNAME
            ATLANTIS_GH_TOKEN: $GH_ATLANTIS_TOKEN
            ATLANTIS_GH_WEBHOOK_SECRET: $WEBHOOK_SECRET
            ATLANTIS_REPO_ALLOWLIST: 'github.com/romeshb29/atlantis-local-poc'
            ATLANTIS_REPO_CONFIG: '/opt/repo.yaml'
            ATLANTIS_ATLANTIS_URL: 'https://41ee-49-207-223-72.ngrok.io'